/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.project.ApplyKarachiMVC.UI;

import com.project.ApplyKarachiMVC.BO.SelectedUniversities;
import com.project.ApplyKarachiMVC.BO.Student;
import com.project.ApplyKarachiMVC.constants.Constants;
import com.project.ApplyKarachiMVC.controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author saad
 */
public class submitForm extends javax.swing.JFrame {

    MainForm mainform=null;
    submitForm submitform=null;
    
    
    
    
    public submitForm() {
        initComponents();
        this.infolbl1.setVisible(false);
    }
    /**
     * Creates new form submitForm
     */
//    public submitForm() {
  //      initComponents();
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fathernametxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        citytxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        countrytxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mobiletxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        statusitem = new javax.swing.JComboBox();
        infolbl1 = new javax.swing.JLabel();
        uploadbtn = new javax.swing.JButton();
        abouttxt = new javax.swing.JTextField();
        imagelbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        next1btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        schoolitem = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        collegeitem = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        schoolnametxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        schoolyeartxt = new javax.swing.JTextField();
        mObtaintxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        mTotaltxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        collegenametxt = new javax.swing.JTextField();
        collegeyeartxt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        iObtaintxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        iTotaltxt = new javax.swing.JTextField();
        infolbl2 = new javax.swing.JLabel();
        errormsglbl1 = new javax.swing.JLabel();
        errormsglbl2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        next2btn = new javax.swing.JButton();
        previousbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        oneitem = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        seconditem = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        thirditem = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        savebtn3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        interestxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        previous2btn = new javax.swing.JButton();
        infolbl3 = new javax.swing.JLabel();
        selectbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        universityjList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        selecteduniversitiesList = new javax.swing.JList();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("First name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Last name");

        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });

        lnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnametxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Father name");

        fathernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathernametxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("City/Town");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Country");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Address");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Mobile number");

        mobiletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiletxtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Martial Status");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Apply Karachi");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("About you :");

        statusitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married" }));
        statusitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusitemActionPerformed(evt);
            }
        });

        infolbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infolbl1.setForeground(new java.awt.Color(255, 0, 51));
        infolbl1.setText("Some Fields are missing !!!");

        uploadbtn.setText("upload");
        uploadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbtnActionPerformed(evt);
            }
        });

        abouttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abouttxtActionPerformed(evt);
            }
        });

        imagelbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        imagelbl.setText("Image");

        jButton1.setText("back to main menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        next1btn.setText("next");
        next1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(infolbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(statusitem, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fathernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(countrytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addGap(266, 266, 266)))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(next1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addComponent(abouttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(67, 67, 67)
                                    .addComponent(jLabel12))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadbtn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(imagelbl)
                        .addGap(16, 16, 16)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagelbl)
                            .addComponent(jLabel12))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(infolbl1)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(uploadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fathernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countrytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(mobiletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(statusitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abouttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Personal Information", jPanel1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Apply Karachi");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Higher Secondary Education Information(e.g intermediate/A-Levels)");

        jLabel1.setText("Board of Education");

        schoolitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Karachi Intermediate Board", "Sindh Intermediate Board", "Agha Khan Intermediate Board", "American High School Diploma", "Federal Board" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Secondary School Information(e.g Matric/O-Levels)");

        jLabel15.setText("Board of Education");

        collegeitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Karachi Intermediate Board", "Sindh Intermediate Board", "Agha Khan Intermediate Board", "American High School Diploma", "Federal Board" }));

        jLabel21.setText("School name :");

        jLabel23.setText("Marks Obtained");

        mObtaintxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mObtaintxtActionPerformed(evt);
            }
        });

        jLabel24.setText("out of");

        mTotaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTotaltxtActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Qualifying Exam Details:(Matric)");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Qualifying Exam Details:(Intermediate)");

        jLabel27.setText("College name :");

        collegeyeartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeyeartxtActionPerformed(evt);
            }
        });

        jLabel28.setText("Marks Obtained");

        jLabel29.setText("Out of");

        infolbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infolbl2.setForeground(new java.awt.Color(255, 0, 51));
        infolbl2.setText("Some Fields are missing !!!");

        errormsglbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        errormsglbl1.setForeground(new java.awt.Color(255, 0, 51));
        errormsglbl1.setText("Obtain marks greater than total marks");

        errormsglbl2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        errormsglbl2.setForeground(new java.awt.Color(255, 0, 51));
        errormsglbl2.setText("Obtain marks greater than total marks");

        jButton3.setText("back to main menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel31.setText("passing year");

        jLabel32.setText("passing year");

        next2btn.setText("Next");
        next2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next2btnActionPerformed(evt);
            }
        });

        previousbtn.setText("previous");
        previousbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(73, 73, 73)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(infolbl2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(schoolitem, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel21))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(mObtaintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(mTotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(errormsglbl1))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(schoolnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(schoolyeartxt, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))))))
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(collegeitem, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(collegenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(collegeyeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(iObtaintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(previousbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(next2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(iTotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(errormsglbl2)))))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(infolbl2)
                .addGap(64, 64, 64)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(schoolitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(collegeitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(schoolnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schoolyeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(mObtaintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(mTotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errormsglbl1))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(collegenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collegeyeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(iObtaintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(iTotaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errormsglbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previousbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Educational Background", jPanel2);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Apply Karachi");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Please indicate degree of program you intend to apply to");

        jLabel17.setText("Degree Program 1st preference");

        oneitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BE (Mechnical)", "BE (Electrical)", "BS(Computer Science)", "BS(Fianance)", "Business Administration (BBA)" }));
        oneitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneitemActionPerformed(evt);
            }
        });

        jLabel18.setText("Degree Program 2nd preference");

        seconditem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BE (Mechnical)", "BE (Electrical)", "BS(Computer Science)", "BS(Fianance)", "Business Administration (BBA)" }));

        jLabel19.setText("Degree Program 3rd preference");

        thirditem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BE (Mechnical)", "BE (Electrical)", "BS(Computer Science)", "BS(Fianance)", "Business Administration (BBA)" }));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Why are you interested in this particular program and what do you aim to gain from it?");

        savebtn3.setText("Save and Continue");
        savebtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtn3ActionPerformed(evt);
            }
        });

        jLabel30.setText("Select University :");

        interestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestxtActionPerformed(evt);
            }
        });

        jButton4.setText("Back to main menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        previous2btn.setText("Previous");
        previous2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous2btnActionPerformed(evt);
            }
        });

        infolbl3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infolbl3.setForeground(new java.awt.Color(255, 0, 51));
        infolbl3.setText("Some feilds are missing !!!");

        selectbtn.setText("select");
        selectbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectbtnActionPerformed(evt);
            }
        });

        universityjList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "NED", "Sir Syed University", "NUST", "FAST", "DHA SUFFA University", "Indus University", "Iqra University", "Bahria University", "IoBM", "SZABIST", "MAJU", "Karachi University", "IBA ", "DOW", "Greenwich", "SMDC", "Agha Khan University", "FUUAST", "KANUPP", "Preston", "Indus Valley School of Arts", "Hamdard", "BIZTEK", "IIEE", "Dawood Engineering University", "Zia Uddin University", "Baqai Medical College", "Karachi School of Arts", "Jinnah Women University", "Usman Institute of Technology", "KASBIT", "Karachi School of Business LeaderShip", "Textile Institute of Pakistan", "PAF-KIET", "Sindh Madarsatul Islam University", "College of Home Economics" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        universityjList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                universityjListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(universityjList);

        jScrollPane3.setViewportView(selecteduniversitiesList);

        jLabel33.setText("Selected Universities");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(73, 73, 73)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infolbl3)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel18))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(6, 6, 6)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(thirditem, 0, 152, Short.MAX_VALUE)
                                            .addComponent(oneitem, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                            .addComponent(seconditem, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel30)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addGap(23, 23, 23))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(interestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previous2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(savebtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infolbl3)
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(oneitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(seconditem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(thirditem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(40, 40, 40)
                .addComponent(interestxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Intended Program", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fathernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fathernametxtActionPerformed

    private void lnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnametxtActionPerformed

    private void mTotaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTotaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTotaltxtActionPerformed

    private void oneitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneitemActionPerformed

    private void collegeyeartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeyeartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeyeartxtActionPerformed

    private void mObtaintxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mObtaintxtActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_mObtaintxtActionPerformed

    private void statusitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusitemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusitemActionPerformed

    private void mobiletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobiletxtActionPerformed

    private void abouttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abouttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abouttxtActionPerformed

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void uploadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbtnActionPerformed
        // TODO add your handling code here:
        JFileChooser abc = new JFileChooser();
        int showDialog = abc.showDialog(abc, null);
        imagelbl.setIcon((Icon) abc.getSelectedFile());
        
        
    }//GEN-LAST:event_uploadbtnActionPerformed

    private void savebtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtn3ActionPerformed
        Object [] parameters = new Object [24];//[40];
        Object [] returnObj = null;
        parameters [0] = fnametxt.getText();
        parameters [1] = lnametxt.getText();
        parameters [2] = fathernametxt.getText();
        parameters [3] = addresstxt.getText();
        parameters [4] = citytxt.getText();
        parameters [5] = countrytxt.getText();
        parameters [6] = mobiletxt.getText();
        parameters [7] = statusitem.getSelectedItem();
        parameters [8] = abouttxt.getText();
        parameters [9] = schoolitem.getSelectedItem();
        parameters [10] = collegeitem.getSelectedItem();
        parameters [11] = schoolnametxt.getText();
        parameters [12] = schoolyeartxt.getText();
        
        String schoolMarks= (String)(mObtaintxt.getText());        
        parameters [13] = schoolMarks;
        
        String schoolTotalMarks= (String)(mTotaltxt.getText());        
        parameters [14] = schoolTotalMarks;
        
        parameters [15] = collegenametxt.getText();
        parameters [16] = collegeyeartxt.getText();
        
        String collegeMarks=(String) (iObtaintxt.getText());        
        parameters [17] = collegeMarks; 
        
       String collegeTotalMarks=(String) (iTotaltxt.getText());
        parameters [18] = collegeTotalMarks;
        
        parameters [19] = oneitem.getSelectedItem();
        parameters [20] = seconditem.getSelectedItem();
        parameters [21] = thirditem.getSelectedItem();
        
        
        List<String> temp_str = new ArrayList<>();
        
       
        parameters [22] = interestxt.getText();
        
        
/*      parameters [22] = nedbox.getText();
        parameters [23] = fastbox.getText();
        parameters [24] = iqrabox.getText();
        parameters [25] = suffabox.getText();
        parameters [26] = kubox.getText();
        parameters [27] = indusbox.getText();
        parameters [28] = smdcbox.getText();
        parameters [29] = ssuetbox.getText();
        parameters [30] = Hamdardbox.getText();
        parameters [31] = pafbox.getText();
        parameters [32] = szabistbox.getText();
        parameters [33] = prestonbox.getText();
        parameters [34] = ibabox.getText();
        parameters [35] = dowbox.getText();
        parameters [36] = aghabox.getText();
        parameters [37] = bahriabox.getText();
        parameters [38] = majubox.getText();
        parameters [39] = interestxt.getText();
*/        

        
        int a = schoolMarks.compareTo(schoolTotalMarks);
        int b = collegeMarks.compareTo(collegeTotalMarks);
      
        
        if(parameters[0].equals("") || parameters[1].equals("") || parameters[2].equals("") || parameters[3].equals("") || parameters[4].equals("") || parameters[5].equals("") || parameters[8].equals("") || parameters[11].equals("") || parameters[12].equals("") || parameters[13].equals("") || parameters[14].equals("") || parameters[15].equals("") || parameters[16].equals("") || parameters[17].equals("") || parameters[18].equals("")){
            System.out.print(parameters[0]);
            infolbl1.setVisible(true);
            infolbl2.setVisible(true);
            infolbl3.setVisible(true);
            
        }
        
        else if(a == 1 || b == 1) {
        
            infolbl1.setVisible(false);
            infolbl2.setVisible(false);
            errormsglbl1.setVisible(true);
            errormsglbl2.setVisible(true);
        }
        else{
        Controller controller = new Controller();
        returnObj = controller.processRequest(Constants.applicantAction, parameters);
            infolbl1.setVisible(false);
            infolbl2.setVisible(false);
            errormsglbl1.setVisible(false);
            errormsglbl2.setVisible(false);

      
        int result = JOptionPane.showConfirmDialog(this, "Your form has been submitted to selected universities!", "Thanks for Applying", JOptionPane.PLAIN_MESSAGE);     
        if(result == JOptionPane.OK_OPTION) {
            mainform = new MainForm();
            this.setVisible(false);
            mainform.setVisible(true); 
        }          
        }        
//        jTabbedPane1.setSelectedIndex(3);
    // TODO add your handling code here:
    }//GEN-LAST:event_savebtn3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            infolbl1.setVisible(false);
            infolbl2.setVisible(false);
            infolbl3.setVisible(false);
            errormsglbl1.setVisible(false);
            errormsglbl2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int result = JOptionPane.showConfirmDialog(this, "Are you sure? You will lose unsaved changes!", "Submission Form closing... ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION){
        
        
        mainform = new MainForm();
        this.setVisible(false);
        mainform.setVisible(true); 
        }else
        {
        this.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   int result = JOptionPane.showConfirmDialog(this, "Are you sure? You will lose unsaved changes!", "Submission Form closing... ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION){
        
        
        mainform = new MainForm();
        this.setVisible(false);
        mainform.setVisible(true); 
        }else
        {
        this.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void next1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1btnActionPerformed
        // TODO add your handling code here:
    if (jTabbedPane1.getTabCount() == 0) {

    System.err.println("No Tabs In Pane");

    return;

  }
  // for moving right
  if (evt.getSource() == next1btn) {

    if(jTabbedPane1.getSelectedIndex() == 0)

      jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()-2);

    else {

      jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()-3);

    }

  }
  // for moving left
  /*if (evt.getSource() == cancel2btn) {

    if(jTabbedPane1.getSelectedIndex() == jTabbedPane1.getTabCount()-1)

      jTabbedPane1.setSelectedIndex(0);

    else

      jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()+1);

  }*/
    }//GEN-LAST:event_next1btnActionPerformed

    private void next2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next2btnActionPerformed
        // TODO add your handling code here:
         if (jTabbedPane1.getTabCount() == 0) {

    System.err.println("No Tabs In Pane");

    return;

  }
  // for moving right
  if (evt.getSource() == next2btn) {

    if(jTabbedPane1.getSelectedIndex() == 1)

      jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount()- 1);

    else {

      jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()-3);

    }

  }
  // for moving left
  /*if (evt.getSource() == cancel2btn) {

    if(jTabbedPane1.getSelectedIndex() == jTabbedPane1.getTabCount()-1)

      jTabbedPane1.setSelectedIndex(0);

    else

      jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()+1);

  }*/
    }//GEN-LAST:event_next2btnActionPerformed

    private void previousbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousbtnActionPerformed
        // TODO add your handling code here:
          // for moving left
  if (evt.getSource() == previousbtn) {

    if(jTabbedPane1.getSelectedIndex() == jTabbedPane1.getTabCount()-2)

      jTabbedPane1.setSelectedIndex(0);

    else

      jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()-1);

  }
    }//GEN-LAST:event_previousbtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  int result = JOptionPane.showConfirmDialog(this, "Are you sure? You will lose unsaved changes!", "Submission Form closing... ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION){
        
        
        mainform = new MainForm();
        this.setVisible(false);
        mainform.setVisible(true); 
        }else
        {
        this.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void previous2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous2btnActionPerformed
        // TODO add your handling code here:
    if (evt.getSource() == previous2btn) {

    if(jTabbedPane1.getSelectedIndex() == jTabbedPane1.getTabCount()-2)

      jTabbedPane1.setSelectedIndex(1);

    else

      jTabbedPane1.setSelectedIndex(jTabbedPane1.getSelectedIndex()-1);

  
        }  
    }//GEN-LAST:event_previous2btnActionPerformed

    private void selectbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectbtnActionPerformed
        // TODO add your handling code here:
        selecteduniversitiesList.setModel(model);
        model.addElement(a);
    }//GEN-LAST:event_selectbtnActionPerformed

    private void interestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestxtActionPerformed

    private void universityjListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_universityjListMouseClicked
       temp = universityjList.getSelectedIndex();
       a = (String) universityjList.getModel().getElementAt(temp);
    }//GEN-LAST:event_universityjListMouseClicked
    DefaultListModel model = new DefaultListModel();
    
    int temp = 0, temp1;
    String a = null;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(submitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(submitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(submitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(submitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new submitForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abouttxt;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JTextField citytxt;
    private javax.swing.JComboBox collegeitem;
    private javax.swing.JTextField collegenametxt;
    private javax.swing.JTextField collegeyeartxt;
    private javax.swing.JTextField countrytxt;
    private javax.swing.JLabel errormsglbl1;
    private javax.swing.JLabel errormsglbl2;
    private javax.swing.JTextField fathernametxt;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JTextField iObtaintxt;
    private javax.swing.JTextField iTotaltxt;
    private javax.swing.JLabel imagelbl;
    private javax.swing.JLabel infolbl1;
    private javax.swing.JLabel infolbl2;
    private javax.swing.JLabel infolbl3;
    private javax.swing.JTextField interestxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JTextField mObtaintxt;
    private javax.swing.JTextField mTotaltxt;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JButton next1btn;
    private javax.swing.JButton next2btn;
    private javax.swing.JComboBox oneitem;
    private javax.swing.JButton previous2btn;
    private javax.swing.JButton previousbtn;
    private javax.swing.JButton savebtn3;
    private javax.swing.JComboBox schoolitem;
    private javax.swing.JTextField schoolnametxt;
    private javax.swing.JTextField schoolyeartxt;
    private javax.swing.JComboBox seconditem;
    private javax.swing.JButton selectbtn;
    private javax.swing.JList selecteduniversitiesList;
    private javax.swing.JComboBox statusitem;
    private javax.swing.JComboBox thirditem;
    private javax.swing.JList universityjList;
    private javax.swing.JButton uploadbtn;
    // End of variables declaration//GEN-END:variables
}
